import assert from 'node:assert/strict';
import {test} from 'vitest';
import {verifyModelParityCase,verifyModelParityMatrix} from '../scripts/model-parity-evidence.mjs';

const input={text:'model-parity marker'};
const expected=(provider='openai',surface='tool')=>({model:`${provider}/${provider==='openai'?'gpt-5.6-sol':'qwen3.5:4b'}`,runtimeOwner:{kind:'harness',id:provider==='openai'?'codex':'openclaw'},agentId:'main',sessionKey:'session',sessionId:'session-id',definitionId:'saved-loop',revision:7,nodeId:'inference',reasoning:'low',input,...surface==='tool'?{requestId:'request-1'}:{}});
const run=(provider='openai',surface='tool',id=`run-${provider}-${surface}`)=>{const e=expected(provider,surface),[p,m]=e.model.split('/');return {id,state:'completed',source:{'session-action':'session-action',command:'command',tool:'tool'}[surface],owner:{agentId:e.agentId,sessionKey:e.sessionKey,sessionId:e.sessionId},definition:{id:e.definitionId,revision:e.revision,slug:'parity-loop',nodes:[{id:'inference',kind:'inference'}]},input,executionSettings:{model:e.model,reasoning:e.reasoning},outputs:{inference:{provider:p,model:m,agentId:'main',execution:{owner:e.runtimeOwner},settings:{requested:{model:e.model,reasoning:e.reasoning},applied:'unknown'}}}};};
const history=(provider='openai',r=run(provider))=>{const e=expected(provider),[p,m]=e.model.split('/',2),call=provider==='openai'?{id:'call-1',type:'toolCall',name:'loops_run',arguments:{slug:'parity-loop',input,requestId:e.requestId}}:{id:'call-1',type:'toolCall',name:'tool_call',arguments:{id:'openclaw:loops-poc:loops_run',args:{slug:'parity-loop',input,requestId:e.requestId}}};const result=provider==='openai'?JSON.stringify({id:r.id}):JSON.stringify({tool:{id:'openclaw:loops-poc:loops_run',name:'loops_run'},result:{content:[{text:JSON.stringify({id:r.id})}],details:{id:r.id}}});return {sessionKey:e.sessionKey,sessionId:e.sessionId,messages:[{role:'assistant',provider:p,model:m,content:[call]},{role:'toolResult',toolCallId:'call-1',toolName:call.name,isError:false,content:[{type:'text',text:result}]}]};};
const rejects=(change,provider='openai',surface='tool')=>{const r=run(provider,surface),e=expected(provider,surface),h=history(provider,r);change({r,e,h});assert.throws(()=>verifyModelParityCase({surface,expected:e,run:r,history:h}),/rejected/);};

test('verifies actual-shape Codex and Ollama tool transcripts',()=>{for(const provider of ['openai','ollama']){const r=run(provider),receipt=verifyModelParityCase({surface:'tool',expected:expected(provider),run:r,history:history(provider,r)});assert.equal(receipt.model,expected(provider).model);assert.equal(receipt.limits.appliedReasoning,'unknown');}});
test('accepts a host-resolved short tool alias only with canonical result attribution',()=>{
  const r=run('ollama'),h=history('ollama',r);h.messages[0].content[0].arguments.id='loops_run';
  assert.equal(verifyModelParityCase({surface:'tool',expected:expected('ollama'),run:r,history:h}).runtimeOwner.id,'openclaw');
  const result=JSON.parse(h.messages[1].content[0].text);result.tool.id='openclaw:another-plugin:loops_run';h.messages[1].content[0].text=JSON.stringify(result);
  assert.throws(()=>verifyModelParityCase({surface:'tool',expected:expected('ollama'),run:r,history:h}),/rejected/);
});
test('rejects wrong pinned model, runtime, session, source, revision, and reasoning',()=>{
  rejects(({r})=>r.executionSettings.model='openai/other');rejects(({r})=>r.outputs.inference.model='other');rejects(({r})=>r.outputs.inference.execution.owner.id='openclaw');rejects(({r})=>r.owner.sessionId='other');rejects(({r})=>r.source='command');rejects(({r})=>r.definition.revision=8);rejects(({r})=>r.executionSettings.reasoning='off');rejects(({r})=>delete r.executionSettings.reasoning);rejects(({r})=>r.outputs.inference.settings.requested.reasoning='off');rejects(({r})=>r.input={text:'other'});
});
test('rejects absent, fabricated, mismatched, and failed tool proof',()=>{
  rejects(({h})=>h.messages=[]);rejects(({r,h})=>h.messages=[{role:'assistant',content:[{type:'text',text:`Run: ${r.id}`}]}]);rejects(({h})=>h.sessionKey='other');rejects(({h})=>h.messages[0].content[0].name='tool_search');rejects(({h})=>h.messages[0].content[0].id='');rejects(({h})=>h.messages[1].toolCallId='other');rejects(({h})=>h.messages[1].toolName='other');rejects(({h})=>h.messages[1].isError=true);rejects(({h})=>h.messages[1].content[0].text=JSON.stringify({id:'other'}));rejects(({h})=>h.messages[0].content[0].arguments.requestId='other');
  rejects(({h})=>h.messages[0].model='other');rejects(({h})=>h.messages[1].content[0].text=JSON.stringify({tool:{id:'wrong',name:'loops_run'},result:{details:{id:'run-ollama-tool'}}}),'ollama');rejects(({h})=>h.messages[1].content[0].text=JSON.stringify({tool:{id:'openclaw:loops-poc:loops_run',name:'loops_run'},result:{isError:true,details:{id:'run-ollama-tool'}}}),'ollama');
});
test('accepts reordered input and provider/model names with a slash',()=>{const e=expected();e.model='openai/models/gpt-5.6-sol';const r=run();r.executionSettings.model=e.model;r.outputs.inference.model='models/gpt-5.6-sol';r.outputs.inference.settings.requested.model=e.model;r.input={b:2,a:1};e.input={a:1,b:2};const h=history();h.messages[0].model='models/gpt-5.6-sol';h.messages[0].content[0].arguments.input={a:1,b:2};assert.equal(verifyModelParityCase({surface:'tool',expected:e,run:r,history:h}).model,e.model);});
test('rejects an invented UI surface and keeps session-action native-editor proof separate',()=>{const r=run('openai','session-action'),receipt=verifyModelParityCase({surface:'session-action',expected:expected('openai','session-action'),run:r});assert.equal(receipt.evidenceScope,'public-backend-route');assert.equal(receipt.limits.nativeEditor,'unverified-separate');assert.equal(Object.hasOwn(receipt,'nativeUi'),false);assert.throws(()=>verifyModelParityCase({surface:'ui',expected:expected('openai','session-action'),run:r}),/surface must be/);});
test('matrix requires every provider/surface route, unique runs, and one definition',()=>{
  const cases=['openai','ollama'].flatMap(provider=>['session-action','command','tool'].map(surface=>{const r=run(provider,surface);return {surface,expected:expected(provider,surface),run:r,...surface==='tool'?{history:history(provider,r)}:{}};}));
  const matrix=verifyModelParityMatrix(cases);assert.equal(matrix.cases.length,6);assert.equal(matrix.evidenceScope,'public-backend-routes');assert.equal(matrix.limits.nativeEditor,'unverified-separate');
  assert.throws(()=>verifyModelParityMatrix(cases.slice(1)),/six cases/);
  const missing=structuredClone(cases);missing[5].surface='command';missing[5].run.source='command';assert.throws(()=>verifyModelParityMatrix(missing),/missing openclaw\/tool/);
  const duplicate=structuredClone(cases);duplicate[1].run.id=duplicate[0].run.id;assert.throws(()=>verifyModelParityMatrix(duplicate),/duplicate/);
  const wrongDefinition=structuredClone(cases);wrongDefinition[5].expected.definitionId='other';assert.throws(()=>verifyModelParityMatrix(wrongDefinition),/definition/);
  const changedModel=structuredClone(cases);changedModel[0].expected.model='openai/another';changedModel[0].run.executionSettings.model='openai/another';changedModel[0].run.outputs.inference.model='another';changedModel[0].run.outputs.inference.settings.requested.model='openai/another';assert.throws(()=>verifyModelParityMatrix(changedModel),/settings across routes/);
  const changedContent=structuredClone(cases);changedContent[0].run.definition.nodes[0].label='Changed';assert.throws(()=>verifyModelParityMatrix(changedContent),/definition content/);
  const differentNodes=structuredClone(cases);for(const item of differentNodes){item.run.definition.nodes.push({id:'alternate',kind:'inference'});item.run.outputs.alternate=structuredClone(item.run.outputs.inference);}for(const item of differentNodes.slice(3))item.expected.nodeId='alternate';assert.throws(()=>verifyModelParityMatrix(differentNodes),/one inherited inference node/);
  const explicitOverride=structuredClone(cases);explicitOverride[0].run.definition.nodes[0].model=explicitOverride[0].expected.model;assert.throws(()=>verifyModelParityMatrix(explicitOverride),/must inherit model and reasoning/);
  const explicitReasoning=structuredClone(cases);explicitReasoning[0].run.definition.nodes[0].reasoning=explicitReasoning[0].expected.reasoning;assert.throws(()=>verifyModelParityMatrix(explicitReasoning),/must inherit model and reasoning/);
  const configuredTargets=structuredClone(differentNodes);for(const item of configuredTargets)for(const [index,node] of item.run.definition.nodes.entries()){node.model=cases[index===0?0:3].expected.model;node.reasoning=cases[index===0?0:3].expected.reasoning;}assert.throws(()=>verifyModelParityMatrix(configuredTargets),/must inherit model and reasoning/);
  const advanced=structuredClone(cases);for(const item of advanced)item.run.definition.nodes[0].advanced={temperature:0};assert.equal(verifyModelParityMatrix(advanced).cases.length,6);
});
