import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createServer} from 'node:http';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright-core';

const root=resolve(import.meta.dirname,'../..');
const budgets={definitionBytes:4194304,inputBytes:1048576,promptBytes:1048576,defaultOutputBytes:1048576,defaultExecutions:1000,defaultRepeat:3};
const parameters=[
  {key:'temperature',label:'Temperature',type:'number',support:'advisory',reason:'Synthetic browser transport.',minimum:0},
  {key:'maxTokens',label:'Output tokens',type:'integer',support:'advisory',reason:'Synthetic browser transport.',minimum:1},
];

function harness(){return `
  import React from 'react'; import {createRoot} from 'react-dom/client'; import {Editor} from './src/editor.tsx'; import {initialContext,applyContextPatch,projectContext} from './src/context.ts'; import {bind} from './src/graph.ts';
  const parameters=${JSON.stringify(parameters)}, budgets=${JSON.stringify(budgets)};
  const clone=value=>structuredClone(value), listeners=new Set(), records=new Map(), calls=[], pendingRuns=new Map(), deferredDrafts=[], deferredLoads=[], sessionListeners=new Set(); let delayDrafts=0,delayLoads=0,localDraftWriteFailures=0;
  const record=definition=>({definition,enabledRevision:null,publishedRevision:null,grants:definition.capabilities,revisions:{[definition.revision]:clone(definition)}});
  const emit=()=>listeners.forEach(listener=>listener({}));
  const page=()=>({items:[...records.values()].filter(item=>!item.archived&&!item.deletedAt).map(item=>({id:item.definition.id,slug:item.definition.slug,name:item.definition.name,description:item.definition.description,revision:item.definition.revision,enabledRevision:item.enabledRevision,publishedRevision:item.publishedRevision,hasDraft:item.publishedRevision!==item.definition.revision,capabilities:item.definition.capabilities,archived:false})),nextCursor:null,total:records.size,offset:0});
  const save=(definition,enabled,mode,expectedRevision)=>{let item=records.get(definition.id);if(expectedRevision!==undefined&&expectedRevision!==(item?.definition.revision??0))throw Error('revision changed');const revision=(item?.definition.revision??0)+1;const next={...clone(definition),revision};if(!item)item=record(next);else {item.definition=next;item.revisions={...item.revisions,[revision]:clone(next)};}if(enabled){item.enabledRevision=revision;item.publishedRevision=revision;} records.set(next.id,item);calls.push({mode,definition:clone(next),enabled:item.enabledRevision,published:item.publishedRevision});emit();return {record:clone(item),issues:[]};};
  const runReceipt=run=>({id:run.id,state:run.state,owner:run.owner,source:run.source,definition:{id:run.definition.id,slug:run.definition.slug,name:run.definition.name,revision:run.definition.revision},executions:run.executions,createdAt:run.createdAt,updatedAt:run.updatedAt,models:[],pending:run.pending,steps:[],inspection:'Synthetic mounted-browser checkpoint receipt.'});
  const addPendingRun=(id,state,pending)=>{const definition=clone([...records.values()][0].definition),at='2026-09-21T18:00:00.000Z',sessionKey='agent:main:editor-browser';pendingRuns.set(id,{id,requestKey:id,requestFingerprint:id,owner:{agentId:'main',sessionKey,sessionId:sessionKey},source:'session-action',definition,input:{},state,cursor:definition.nodes[0].id,outputs:{},trace:[],executions:0,activeMs:0,createdAt:at,updatedAt:at,pending});emit();};
  const addTypedContextRun=id=>{const definition=clone([...records.values()][0].definition),at='2026-09-21T18:00:00.000Z',sessionKey='agent:main:editor-browser',input={text:'fixture'},summary=definition.nodes.find(node=>node.id==='summary'),returned=definition.nodes.find(node=>node.id==='return');if(!summary?.context||!returned?.context)throw Error('Context fixture requires authored Summary and Return policies.');const context=applyContextPatch(initialContext(input),summary.id,summary.context,0,value=>bind(value,{input,nodes:{summary:0}}),()=> 'b'.repeat(64)),result=bind(returned.value,{input,nodes:{summary:0},context:projectContext(context,returned.context)});pendingRuns.set(id,{id,requestKey:id,requestFingerprint:id,owner:{agentId:'main',sessionKey,sessionId:sessionKey},source:'session-action',definition,input,state:'completed',cursor:'return',outputs:{summary:0,return:result},trace:[],executions:3,activeMs:0,createdAt:at,updatedAt:at,result,context});emit();};
  const action=async(id,payload)=>{calls.push({id,payload:clone(payload)});if(id==='capabilities')return {model:'fake/default',runtime:'synthetic browser transport',configured:true,authorized:true,available:true,parameters,budgets,concurrency:1,notes:['No provider was called.']};if(id==='browse')return page();if(id==='history'){const items=[...pendingRuns.values()].map(run=>({id:run.id,slug:run.definition.slug,revision:run.definition.revision,state:run.state,createdAt:run.createdAt,updatedAt:run.updatedAt,executions:run.executions}));return {items,nextCursor:null,total:items.length};}if(id==='inspect')return clone(pendingRuns.get(payload.runId));if(id==='resume'||id==='review')return runReceipt(pendingRuns.get(payload.runId));if(id==='load'){if(delayLoads){delayLoads--;return new Promise((resolve,reject)=>deferredLoads.push({payload,resolve,reject}));}if(!records.has(payload.id))throw Error('Loop not found.');return clone(records.get(payload.id));}if(id==='save')return save(payload.definition,payload.enabled===true,'save',payload.expectedRevision);if(id==='draft'){if(delayDrafts){delayDrafts--;return new Promise((resolve,reject)=>deferredDrafts.push({payload,resolve,reject}));}return save(payload.definition,false,'draft',payload.expectedRevision);}if(id==='publish'){const item=records.get(payload.id);item.enabledRevision=payload.revision;item.publishedRevision=payload.revision;calls.push({mode:'publish',revision:payload.revision});emit();return clone(item);}if(id==='enable'){const item=records.get(payload.id);item.enabledRevision=payload.enabled?payload.revision:null;emit();return clone(item);}if(id==='restore'){const item=records.get(payload.id), base=clone(item.revisions[payload.revision]);return save({...base,id:item.definition.id,slug:item.definition.slug},false,'restore');}throw Error('Unhandled browser transport operation: '+id);};
  const sessions=[{key:'agent:main:editor-browser',agentId:'main',label:'Editor browser regression'},{key:'agent:main:editor-browser-2',agentId:'main',label:'Second main conversation'},{key:'agent:other:editor-browser',agentId:'other',label:'Other editor scope'}]; let visibleSessions=sessions;
  const publishSessions=()=>sessionListeners.forEach(listener=>listener({result:{sessions:visibleSessions}}));
  const host={apiVersion:1,pluginId:'loops-poc',signal:new AbortController().signal,basePath:'/',locale:'en',redact:text=>text,connection:{connected:true},components:{},request:async(_method,params)=>({ok:true,result:await action(params.actionId,params.payload)}),onEvent:(event,listener)=>{if(event==='plugin.loops-poc.changed'){listeners.add(listener);return ()=>listeners.delete(listener);}return ()=>{};},subscribe:()=>()=>{},sessions:{rows:sessions,selectedKey:sessions[0].key,normalizeKey:key=>key,refresh:async()=>{},observe:(_query,listener)=>{sessionListeners.add(listener);listener({result:{sessions:visibleSessions}});return {dispose:()=>sessionListeners.delete(listener)};},open:()=>{},create:async()=>visibleSessions[0].key,patch:async()=>{}},agents:{rows:[{id:'main',name:'Main'},{id:'other',name:'Other'}],selectedId:'main',defaultId:'main',scopeId:null,select:()=>{},setScope:()=>{},refresh:async()=>{}},navigation:{openPage:()=>{},pageHref:()=>''},ui:{invalidate:()=>{},registerPage:()=>()=>{},registerNavigation:()=>()=>{},registerPanel:()=>()=>{},registerAction:()=>()=>{},registerAccessory:()=>()=>{},registerWidget:()=>()=>{},registerReplacement:()=>()=>{},selectReplacement:()=>{}}};
  const root=createRoot(document.getElementById('app')); globalThis.__editorRegression={calls,records,deferNextDraft:()=>{delayDrafts++;},deferredDraftCount:()=>deferredDrafts.length,resolveNextDraft:()=>{const next=deferredDrafts.shift();if(!next)throw Error('No deferred draft.');next.resolve(save(next.payload.definition,false,'draft',next.payload.expectedRevision));},rejectNextDraft:message=>{const next=deferredDrafts.shift();if(!next)throw Error('No deferred draft.');next.reject(Error(message));},deferNextLoad:()=>{delayLoads++;},deferredLoadCount:()=>deferredLoads.length,resolveNextLoad:()=>{const next=deferredLoads.shift();if(!next)throw Error('No deferred load.');next.resolve(clone(records.get(next.payload.id)));},rejectNextLoad:message=>{const next=deferredLoads.shift();if(!next)throw Error('No deferred load.');next.reject(Error(message));},switchConversation:key=>{const session=sessions.find(item=>item.key===key);if(!session)throw Error('Unknown session.');visibleSessions=[session];publishSessions();},failNextLocalDraftWrite:()=>{const original=globalThis.Storage.prototype.setItem;globalThis.Storage.prototype.setItem=function(key,value){if(String(key).startsWith('loops-editor:v2:')){globalThis.Storage.prototype.setItem=original;localDraftWriteFailures++;throw Error('synthetic local draft write failure');}return original.call(this,key,value);};},localDraftWriteFailures:()=>localDraftWriteFailures,addPendingRun,addTypedContextRun,refresh:emit,unmount:()=>root.unmount()}; root.render(React.createElement(React.StrictMode,null,React.createElement(Editor,{host})));
`}

async function serve(html){
  const server=createServer((request,response)=>{response.writeHead(200,{'content-type':'text/html'});response.end(html);});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  return {server,url:`http://127.0.0.1:${server.address().port}`};
}
const waitFor=async(page,selector)=>page.locator(selector).waitFor({state:'visible',timeout:10_000});

async function verifyEvaluationDraftRaces(browser,url,checks){
  const open=async()=>{const page=await browser.newPage();page.setDefaultTimeout(10_000);await page.goto(url);await waitFor(page,'select[aria-label="Load an example"]');await page.selectOption('select[aria-label="Load an example"]','summarize-text');return page;};
  const addEvaluation=async page=>{await page.selectOption('select[aria-label="Node family"]','evaluate');await page.getByRole('button',{name:'+ Add node'}).click();return page.getByRole('textbox',{name:'JSON Schema',exact:true});};
  {
    const page=await open(),schema=await addEvaluation(page);
    await page.getByRole('button',{name:'Save draft'}).click();await page.getByText('Revision 1 saved as a draft').waitFor();
    await schema.fill('{"type":"string","minLength":1}');await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft());await page.getByRole('button',{name:'Save draft'}).click();await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1);
    await schema.fill('{');await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft());await page.getByText('Revision 2 saved; newer draft edits are retained.').waitFor();
    assert.equal(await schema.inputValue(),'{');assert.equal(await page.getByRole('button',{name:'Save draft'}).isDisabled(),true);checks.push('invalid evaluator text survives a pending save acknowledgment');await page.close();
  }
  {
    const page=await open(),schema=await addEvaluation(page);
    await page.getByRole('button',{name:'Save draft'}).click();await page.getByText('Revision 1 saved as a draft').waitFor();
    await page.evaluate(()=>{globalThis.__editorRegression.deferNextLoad();globalThis.__editorRegression.refresh();});await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===1);
    await schema.fill('{');await page.evaluate(()=>globalThis.__editorRegression.resolveNextLoad());await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===0);await page.waitForTimeout(100);
    assert.equal(await schema.inputValue(),'{');assert.equal(await page.getByRole('button',{name:'Save draft'}).isDisabled(),true);checks.push('invalid evaluator text survives a pending clean refresh');await page.close();
  }
  for(const pending of ['save','refresh']){
    const page=await open();await addEvaluation(page);
    await page.locator('.lp-evaluation-editor select').first().selectOption('predicate');await page.locator('.lp-evaluation-editor select').nth(1).selectOption('equals');
    const expected=page.getByRole('textbox',{name:'Expected JSON value',exact:true});await expected.fill('0');
    await page.getByRole('button',{name:'Save draft'}).click();await page.getByText('Revision 1 saved as a draft').waitFor();
    if(pending==='save'){
      await expected.fill('1');await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft());await page.getByRole('button',{name:'Save draft'}).click();await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1);
    }else{
      await page.evaluate(()=>{globalThis.__editorRegression.deferNextLoad();globalThis.__editorRegression.refresh();});await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===1);
    }
    await expected.fill('{');
    if(pending==='save'){await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft());await page.getByText('Revision 2 saved; newer draft edits are retained.').waitFor();}
    else{await page.evaluate(()=>globalThis.__editorRegression.resolveNextLoad());await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===0);await page.waitForTimeout(100);}
    assert.equal(await expected.inputValue(),'{');assert.equal(await page.getByRole('button',{name:'Save draft'}).isDisabled(),true);checks.push(`invalid predicate text survives a pending ${pending}`);await page.close();
  }
  {
    const page=await open();await page.getByRole('button',{name:'Save draft'}).click();await page.getByText('Revision 1 saved as a draft').waitFor();
    await page.getByLabel('Node label').fill('Changed input');const schema=await addEvaluation(page);await schema.fill('{');await page.getByRole('button',{name:'Undo',exact:true}).click();
    assert.equal(await page.getByText('Finish the invalid evaluator JSON before saving or publishing.').count(),0);assert.equal(await page.getByRole('button',{name:'Save draft'}).isDisabled(),false);
    await page.getByRole('button',{name:'Save draft'}).click();await page.getByText('Revision 2 saved as a draft').waitFor();await page.getByRole('button',{name:'Redo',exact:true}).click();
    assert.equal(await schema.inputValue(),'{');assert.equal(await page.getByRole('button',{name:'Save draft'}).isDisabled(),true);checks.push('Undo excludes an inactive invalid evaluator draft and Redo restores it after save');await page.close();
  }
}

export async function runEditorAdvancedRegression({receiptPath}={}){
  const bundle=await build({stdin:{contents:harness(),resolveDir:root,loader:'ts'},bundle:true,format:'iife',platform:'browser',write:false,target:'es2022'});
  const {server,url}=await serve(`<!doctype html><html><body><div id="app"></div><script>${bundle.outputFiles[0].text}</script></body></html>`);
  let browser; let importDirectory;
  const receipt={runner:'mounted-production-editor-playwright',transport:'synthetic fake backend; no provider invoked',checks:[],errors:[]};
  try {
    browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1440,height:1000}});
    page.setDefaultTimeout(10_000);page.on('pageerror',error=>receipt.errors.push(error.message));page.on('dialog',dialog=>void dialog.accept());
    await page.goto(url); await waitFor(page,'select[aria-label="Load an example"]');
    await page.selectOption('select[aria-label="Load an example"]','summarize-text');
    await page.selectOption('select[aria-label="Node family"]','evaluate'); await page.getByRole('button',{name:'+ Add node'}).click();
    const authorSelection=page.locator('select[aria-label="Select node to edit"]'); const evaluateId=await authorSelection.inputValue();
    await page.getByText('Deterministic evaluation').waitFor(); assert.equal(await page.getByRole('button',{name:'Enable version 3 shared context in this draft'}).count(),0);receipt.checks.push('Evaluate palette addition promotes the draft to version 3'); const evaluationSchema=page.getByRole('textbox',{name:'JSON Schema',exact:true});await evaluationSchema.fill('{');await page.getByRole('alert').filter({hasText:'valid JSON'}).waitFor();assert.equal(await page.getByRole('button',{name:'Save draft'}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Save & publish'}).isDisabled(),true);await authorSelection.selectOption('summary');assert.equal(await page.getByRole('button',{name:'Save draft'}).isDisabled(),true);const invalidRefreshBefore=await page.evaluate(()=>globalThis.__editorRegression.calls.filter(call=>call.id==='load').length);await page.evaluate(()=>globalThis.__editorRegression.refresh());await page.waitForFunction(before=>globalThis.__editorRegression.calls.filter(call=>call.id==='load').length>before,invalidRefreshBefore);await authorSelection.selectOption(evaluateId);assert.equal(await evaluationSchema.inputValue(),'{');await page.getByRole('alert').filter({hasText:'valid JSON'}).waitFor();await evaluationSchema.fill('{"type":"string","minLength":1}');receipt.checks.push('invalid evaluator JSON survives selection unmount and reports its controlled error');
    await page.selectOption('select[aria-label="Node family"]','gate'); await page.getByRole('button',{name:'+ Add node'}).click();
    const gateId=await authorSelection.inputValue(),evaluationChoice=page.getByLabel('Committed Evaluate node'); await evaluationChoice.selectOption(evaluateId); assert.equal(await evaluationChoice.inputValue(),evaluateId);
    const disconnectedIssues=await page.locator('.lp-issues').textContent(); assert.match(disconnectedIssues??'',/Connect|unreachable/); receipt.checks.push('v3 disconnected palette state reports graph validation before publish');
    await page.selectOption('select[aria-label="Node family"]','return'); await page.getByRole('button',{name:'+ Add node'}).click(); const rejectedId=await authorSelection.inputValue();
    const connect=async(source,port,target)=>{await page.selectOption('select[aria-label="Connection source node"]',source);await page.selectOption('select[aria-label="Connection source branch"]',port);await page.selectOption('select[aria-label="Connection target node"]',target);await page.getByRole('button',{name:'Add connection'}).click();};
    await connect('input','next',evaluateId);await connect(evaluateId,'next',gateId);await connect(gateId,'true','summary');await connect(gateId,'false',rejectedId);
    await page.getByText('✓ Valid graph').waitFor(); assert.equal(await page.locator('.lp-issues').count(),0); receipt.checks.push('v3 Evaluate dominates Gate with connected terminal branches');
    await page.selectOption('select[aria-label="Select node to edit"]','summary');
    await page.getByRole('button',{name:'Configure context'}).click(); await page.getByRole('button',{name:'Remove context configuration'}).click(); await page.getByRole('button',{name:'Configure context'}).click();
    await page.getByLabel('Context projection').selectOption('consume'); await page.getByRole('textbox',{name:'Projected path 1',exact:true}).fill('/bad~2pointer'); await page.getByRole('status').getByText(/Use ~0 for ~/).waitFor(); await page.getByRole('textbox',{name:'Projected path 1',exact:true}).fill('/input/text');
    await page.getByLabel('Output patch').selectOption('replace'); await page.getByLabel('Context target JSON Pointer').fill('/result'); await page.getByLabel('Output patch').selectOption('append'); await page.getByLabel('Output patch').selectOption('merge'); await page.getByLabel('Output patch').selectOption('replace'); assert.equal(await page.getByLabel('Context target JSON Pointer').inputValue(),'/result'); await page.getByLabel('Patch source').selectOption('literal'); await page.getByLabel('Literal patch value JSON').fill('0');
    assert.equal(await page.getByLabel('Literal patch value JSON').inputValue(),'0'); receipt.checks.push('explicit v3 context authoring, repair, remove, and patch-mode preservation');
    await page.selectOption('select[aria-label="Select node to edit"]','return'); await page.getByRole('textbox',{name:'Return value or binding',exact:true}).fill('{{context.result}}'); await page.getByRole('button',{name:'Configure context'}).click(); await page.getByLabel('Context projection').selectOption('consume'); await page.getByRole('textbox',{name:'Projected path 1',exact:true}).fill('/result'); receipt.checks.push('explicit consuming Return authoring'); await page.selectOption('select[aria-label="Select node to edit"]','summary');
    await page.locator('details.lp-advanced summary').click();
    const temperature=page.getByLabel(/^Temperature/), maxTokens=page.getByLabel(/^Output tokens/);
    assert.equal(await temperature.inputValue(),''); assert.equal(await maxTokens.inputValue(),'');receipt.checks.push('inherit omits overrides');
    await temperature.fill('0'); assert.equal(await temperature.inputValue(),'0'); receipt.checks.push('explicit temperature zero');
    await maxTokens.fill('64');
    await page.getByRole('textbox',{name:'Model',exact:true}).fill('fake/switched'); assert.equal(await temperature.inputValue(),'0'); assert.equal(await maxTokens.inputValue(),'64'); receipt.checks.push('model switch preserves explicit overrides');
    await page.getByRole('button',{name:'Save & publish'}).click(); await waitFor(page,'text=Revision 1 saved and enabled for chat and UI.');
    const loadsBefore=await page.evaluate(()=>globalThis.__editorRegression.calls.filter(call=>call.id==='load').length); await page.evaluate(()=>globalThis.__editorRegression.refresh()); await page.waitForFunction(before=>globalThis.__editorRegression.calls.filter(call=>call.id==='load').length>before,loadsBefore); assert.equal(await page.getByLabel('Literal patch value JSON').inputValue(),'0'); receipt.checks.push('saved context configuration reloads through the synthetic transport');
    await page.evaluate(()=>globalThis.__editorRegression.addTypedContextRun('context-fixture'));
    await page.locator('select[aria-label="Select run"] option[value="context-fixture"]').waitFor({state:'attached'}); await page.selectOption('select[aria-label="Select run"]','context-fixture'); await page.getByText('Shared context provenance').waitFor();
    await page.getByText('Context version 1',{exact:false}).waitFor(); await page.getByText('v0 → v1 · summary',{exact:true}).waitFor(); await page.getByText('Resolved value SHA-256',{exact:false}).waitFor(); await page.getByRole('heading',{name:'Recorded output',exact:true}).waitFor(); assert.equal(await page.locator('.lp-run-node-detail .lp-full-output').textContent(),'0'); receipt.checks.push('synthetic typed context fixture applies authored patch and consuming Return, then renders provenance');
    await page.evaluate(()=>globalThis.__editorRegression.addPendingRun('empty-wait','waiting',''));
    await page.locator('select[aria-label="Select run"] option[value="empty-wait"]').waitFor({state:'attached'}); await page.selectOption('select[aria-label="Select run"]','empty-wait'); await page.getByRole('button',{name:'Continue'}).waitFor(); await page.getByRole('button',{name:'Continue'}).focus(); await page.keyboard.press('Enter'); await page.waitForFunction(()=>globalThis.__editorRegression.calls.some(call=>call.id==='resume'&&call.payload.runId==='empty-wait')); receipt.checks.push('empty Wait exposes keyboard Continue');
    await page.evaluate(()=>globalThis.__editorRegression.addPendingRun('empty-review','review',''));
    await page.locator('select[aria-label="Select run"] option[value="empty-review"]').waitFor({state:'attached'}); await page.selectOption('select[aria-label="Select run"]','empty-review'); await page.getByRole('button',{name:'Approve'}).waitFor(); await page.getByRole('button',{name:'Reject'}).waitFor(); assert.equal(await page.getByRole('button',{name:'Continue'}).count(),0); await page.getByRole('button',{name:'Approve'}).focus(); await page.keyboard.press('Enter'); await page.waitForFunction(()=>globalThis.__editorRegression.calls.some(call=>call.id==='review'&&call.payload.runId==='empty-review'&&call.payload.decision==='approve')); assert.equal(await page.evaluate(()=>globalThis.__editorRegression.calls.some(call=>call.id==='resume'&&call.payload.runId==='empty-review')),false); receipt.checks.push('empty Human review exposes keyboard approval without a resume bypass');
    await page.getByRole('button',{name:'Reset temperature'}).click(); assert.equal(await temperature.inputValue(),'');
    await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 2 saved as a draft'); receipt.checks.push('single Advanced reset');
    await temperature.fill('0'); await maxTokens.fill('96');
    await page.getByRole('button',{name:'Reset all Advanced settings'}).click(); assert.equal(await temperature.inputValue(),'');
    await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 3 saved as a draft'); receipt.checks.push('all Advanced reset');
    await temperature.fill('0'); await maxTokens.fill('96');
    await page.getByRole('button',{name:'Save & publish'}).click(); await waitFor(page,'text=Revision 4 saved and enabled for chat and UI.'); receipt.checks.push('model switch and publication');
    const [exported]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export',exact:true}).click()]); const exportedPath=await exported.path(); assert.ok(exportedPath,'Export must create a file.');
    const exportedDefinition=JSON.parse(await (await import('node:fs/promises')).readFile(exportedPath,'utf8')); assert.equal(exportedDefinition.nodes.find(node=>node.id==='summary').advanced.temperature,0); receipt.checks.push('export');
    await page.locator('details.lp-versions summary').click(); await page.selectOption('details.lp-versions select','1');
    await page.getByRole('button',{name:'Restore as draft'}).click(); await page.getByRole('button',{name:'Publish r5',exact:true}).waitFor(); await page.selectOption('select[aria-label="Select node to edit"]','summary');
    assert.equal(await temperature.inputValue(),'0'); assert.equal(await maxTokens.inputValue(),'64'); receipt.checks.push('restore preserves publication');
    await page.getByRole('button',{name:'Clone loop'}).click(); await page.selectOption('select[aria-label="Select node to edit"]','summary'); await page.getByRole('button',{name:'Save & publish'}).click(); await waitFor(page,'text=Revision 1 saved and enabled for chat and UI.'); receipt.checks.push('clone');
    importDirectory=await mkdtemp(join(tmpdir(),'loops-editor-import-')); const fixturePath=join(importDirectory,'definition.json'); await writeFile(fixturePath,JSON.stringify({...exportedDefinition,id:'imported-editor',slug:'imported-editor'}));
    const chooserEvent=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Import',exact:true}).click();await (await chooserEvent).setFiles(fixturePath); await waitFor(page,'text=New loop. Choose Save & publish'); await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 1 saved as a draft'); receipt.checks.push('import');
    const loopName=page.getByLabel('Loop name'),fillLoopName=async value=>{if(!await loopName.isVisible())await page.locator('details.lp-definition-settings summary').click();await loopName.fill(value);};
    await fillLoopName('QA delayed save original'); await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await fillLoopName('QA delayed save newer'); await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft()); await waitFor(page,'text=Revision 2 saved; newer draft edits are retained.'); await page.waitForFunction(()=>{for(let index=0;index<globalThis.localStorage.length;index++)if(globalThis.localStorage.getItem(globalThis.localStorage.key(index))?.includes('QA delayed save newer'))return true;return false;}); assert.equal(await loopName.inputValue(),'QA delayed save newer'); await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 3 saved as a draft'); receipt.checks.push('late save success retains newer same-loop edits, its recoverable local draft, and rebases the next save');
    await fillLoopName('QA delayed failure original'); await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await fillLoopName('QA delayed failure newer'); await page.evaluate(()=>globalThis.__editorRegression.rejectNextDraft('synthetic delayed transport failure')); await page.getByRole('button',{name:'Save draft'}).waitFor({state:'visible'}); await page.waitForFunction(()=>!globalThis.document.querySelector('select[aria-label="Authorized chat session"]')?.disabled); assert.equal(await loopName.inputValue(),'QA delayed failure newer'); assert.match(await page.getByRole('alert').textContent(),/earlier save failed; newer draft edits were retained/i); receipt.checks.push('late save failure retains newer local draft and reports the scoped failure');
    await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await fillLoopName('QA delayed conflict newer'); await page.evaluate(()=>globalThis.__editorRegression.rejectNextDraft('revision changed')); await page.waitForFunction(()=>!globalThis.document.querySelector('select[aria-label="Authorized chat session"]')?.disabled); assert.equal(await loopName.inputValue(),'QA delayed conflict newer'); assert.equal(await page.getByRole('region',{name:'Resolve concurrent edits'}).count(),0); receipt.checks.push('late save conflict cannot replace newer draft or open a stale merge');
    await fillLoopName('QA storage rebase original'); await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await fillLoopName('QA storage rebase newer'); await page.waitForFunction(()=>{for(let index=0;index<globalThis.localStorage.length;index++)if(globalThis.localStorage.getItem(globalThis.localStorage.key(index))?.includes('QA storage rebase newer'))return true;return false;}); await page.evaluate(()=>globalThis.__editorRegression.failNextLocalDraftWrite()); await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft()); await page.waitForFunction(()=>globalThis.__editorRegression.localDraftWriteFailures()===1); assert.equal(await loopName.inputValue(),'QA storage rebase newer'); assert.equal(await page.evaluate(()=>{for(let index=0;index<globalThis.localStorage.length;index++)if(globalThis.localStorage.getItem(globalThis.localStorage.key(index))?.includes('QA storage rebase newer'))return true;return false;}),true); receipt.checks.push('same-loop recovery draft survives a local-storage failure during saved-revision rebase');
    await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 5 saved as a draft'); await fillLoopName('QA switch-loop original'); await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await page.locator('.lp-loop-card').filter({hasText:'Summarize text copy'}).click(); await page.waitForFunction(()=>globalThis.document.querySelector('input')&&[...globalThis.document.querySelectorAll('input')].some(input=>input.value==='Summarize text copy')); await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft()); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===0&&!globalThis.document.querySelector('select[aria-label="Authorized chat session"]')?.disabled); assert.equal(await loopName.inputValue(),'Summarize text copy'); receipt.checks.push('late save cannot replace a different selected loop');
    await fillLoopName('QA exact conflict selection'); await page.evaluate(()=>{globalThis.__editorRegression.deferNextDraft();globalThis.__editorRegression.deferNextLoad();}); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await page.evaluate(()=>globalThis.__editorRegression.rejectNextDraft('revision changed')); await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===1); await page.locator('.lp-loop-card').first().click(); await page.waitForFunction(()=>globalThis.document.querySelector('input')&&[...globalThis.document.querySelectorAll('input')].some(input=>input.value==='Summarize text')); await page.evaluate(()=>globalThis.__editorRegression.resolveNextLoad()); await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===0&&!globalThis.document.querySelector('select[aria-label="Authorized chat session"]')?.disabled); assert.equal(await page.getByRole('region',{name:'Resolve concurrent edits'}).count(),0); assert.equal(await page.getByRole('alert').count(),0); receipt.checks.push('late conflict load cannot contaminate a newly selected loop');
    await fillLoopName('QA exact conflict conversation'); await page.evaluate(()=>{globalThis.__editorRegression.deferNextDraft();globalThis.__editorRegression.deferNextLoad();}); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await page.evaluate(()=>globalThis.__editorRegression.rejectNextDraft('revision changed')); await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===1); await page.evaluate(()=>globalThis.__editorRegression.switchConversation('agent:main:editor-browser-2')); await page.waitForFunction(()=>globalThis.document.querySelector('select[aria-label="Authorized chat session"]')?.value==='agent:main:editor-browser-2'); await page.evaluate(()=>globalThis.__editorRegression.rejectNextLoad('synthetic late conflict load failure')); await page.waitForFunction(()=>globalThis.__editorRegression.deferredLoadCount()===0&&!globalThis.document.querySelector('select[aria-label="Authorized chat session"]')?.disabled); assert.notEqual(await loopName.inputValue(),'QA exact conflict conversation'); assert.equal(await page.getByRole('region',{name:'Resolve concurrent edits'}).count(),0); assert.equal(await page.getByRole('alert').count(),0); receipt.checks.push('late conflict-load failure cannot contaminate a new same-agent conversation');
    await fillLoopName('QA scope-switch original'); await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await page.evaluate(()=>globalThis.__editorRegression.switchConversation('agent:other:editor-browser')); await page.selectOption('select[aria-label="Agent"]','other'); await page.waitForFunction(()=>globalThis.document.querySelector('select[aria-label="Agent"]')?.value==='other'); await page.waitForFunction(()=>globalThis.document.querySelector('input')&&[...globalThis.document.querySelectorAll('input')].every(input=>input.value!=='QA scope-switch original')); await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft()); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===0&&!globalThis.document.querySelector('select[aria-label="Authorized chat session"]')?.disabled); assert.notEqual(await loopName.inputValue(),'QA scope-switch original'); receipt.checks.push('late save cannot replace another agent or conversation scope');
    await page.selectOption('select[aria-label="Load an example"]','summarize-text'); await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 1 saved as a draft');
    await fillLoopName('QA undo saved snapshot'); await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await fillLoopName('QA redo newer snapshot'); await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft()); await waitFor(page,'text=Revision 2 saved; newer draft edits are retained.');
    await page.getByRole('button',{name:'Undo',exact:true}).click(); assert.equal(await loopName.inputValue(),'QA undo saved snapshot'); await page.getByRole('button',{name:'Undo',exact:true}).click(); assert.equal(await loopName.inputValue(),'Summarize text'); await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 3 saved as a draft');
    await page.getByRole('button',{name:'Redo',exact:true}).click(); assert.equal(await loopName.inputValue(),'QA undo saved snapshot'); await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 4 saved as a draft'); await page.getByRole('button',{name:'Redo',exact:true}).click(); assert.equal(await loopName.inputValue(),'QA redo newer snapshot'); await page.getByRole('button',{name:'Save draft'}).click(); await waitFor(page,'text=Revision 5 saved as a draft'); assert.equal(await page.getByRole('region',{name:'Resolve concurrent edits'}).count(),0); receipt.checks.push('Undo and Redo retain authored snapshots while saving with every acknowledged revision');
    const state=await page.evaluate(()=>({calls:globalThis.__editorRegression.calls,records:[...globalThis.__editorRegression.records.entries()]})); const advanced=definition=>definition.nodes.find(node=>node.id==='summary').advanced;
    assert.equal(state.records[0][1].definition.nodes.find(node=>node.id==='summary').model,'fake/switched');
    const saved=state.calls.filter(call=>['save','draft','restore'].includes(call.mode)); assert.deepEqual(advanced(saved.find(call=>call.mode==='save'&&call.definition.revision===1).definition),{temperature:0,maxTokens:64}); assert.deepEqual(advanced(saved.find(call=>call.mode==='save'&&call.definition.revision===4).definition),{temperature:0,maxTokens:96});
    assert.equal(saved.find(call=>call.mode==='save'&&call.definition.revision===1).definition.schemaVersion,3);assert.deepEqual(saved.find(call=>call.mode==='save'&&call.definition.revision===1).definition.nodes.filter(node=>node.kind==='evaluate'||node.kind==='gate').map(node=>node.kind),['evaluate','gate']);
    assert.deepEqual(advanced(saved.find(call=>call.mode==='restore').definition),{temperature:0,maxTokens:64}); assert.deepEqual(advanced(state.records.find(([,item])=>item.definition.slug.startsWith('imported-editor-'))[1].definition),{temperature:0,maxTokens:96}); assert.equal(state.records[0][1].publishedRevision,4);assert.equal(state.records[0][1].enabledRevision,4);assert.deepEqual(advanced(saved.find(call=>call.definition.revision===2).definition),{maxTokens:64});assert.ok(!Object.hasOwn(saved.find(call=>call.definition.revision===3).definition.nodes.find(node=>node.id==='summary'),'advanced'));assert.deepEqual(state.records[1][1].definition.nodes,state.records[0][1].definition.nodes);assert.deepEqual(state.records[1][1].definition.edges,state.records[0][1].definition.edges);assert.deepEqual(receipt.errors,[]);assert.equal(await page.getByRole('alert').count(),0);
    await fillLoopName('QA unmount original'); await page.waitForFunction(()=>{for(let index=0;index<globalThis.localStorage.length;index++)if(globalThis.localStorage.getItem(globalThis.localStorage.key(index))?.includes('QA unmount original'))return true;return false;}); await page.evaluate(()=>globalThis.__editorRegression.deferNextDraft()); await page.getByRole('button',{name:'Save draft'}).click(); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===1); await page.evaluate(()=>globalThis.__editorRegression.unmount()); await page.evaluate(()=>globalThis.__editorRegression.resolveNextDraft()); await page.waitForFunction(()=>globalThis.__editorRegression.deferredDraftCount()===0&&globalThis.__editorRegression.calls.some(call=>call.mode==='draft'&&call.definition.name==='QA unmount original')); assert.equal(await page.evaluate(()=>{for(let index=0;index<globalThis.localStorage.length;index++)if(globalThis.localStorage.getItem(globalThis.localStorage.key(index))?.includes('QA unmount original'))return true;return false;}),true); receipt.checks.push('late save after unmount preserves the recoverable snapshot');
    await verifyEvaluationDraftRaces(browser,url,receipt.checks);
    receipt.definitions=state.records.map(([id,item])=>({id,revision:item.definition.revision,enabledRevision:item.enabledRevision,publishedRevision:item.publishedRevision,advanced:advanced(item.definition)}));
    receipt.operations=state.calls.filter(call=>call.mode||call.id).map(call=>call.mode??call.id); receipt.passed=true;
  } catch(error){receipt.failure=error.message;if(receiptPath)await writeFile(receiptPath,JSON.stringify(receipt,null,2)+'\n');throw error;} finally { await browser?.close(); if(importDirectory)await rm(importDirectory,{recursive:true,force:true}); await new Promise(resolve=>server.close(resolve)); }
  if(receiptPath)await writeFile(receiptPath,JSON.stringify(receipt,null,2)+'\n'); return receipt;
}

if(import.meta.url===pathToFileURL(process.argv[1]).href)console.log(JSON.stringify(await runEditorAdvancedRegression(),null,2));
