import { Type } from 'typebox';
import { defineFeatureContract } from 'openclaw/plugin-sdk/feature-contract';
import { DefinitionSchema, DefinitionContentSchema, DefinitionPatchSchema, type Capability } from './graph.js';
import {toolSchema} from './tool-schema.js';
import {outputs} from './output-schemas.js';
import {RetentionPolicySchema} from './retention.js';
const object={additionalProperties:false} as const;
const id=Type.String({minLength:1,maxLength:100});
const runId=Type.Object({runId:id},object);
const empty=Type.Object({},object);
const output=outputs.receipt;
const saved=outputs.saved;
const revision=Type.Integer({minimum:1});
const expectedRevision=Type.Integer({minimum:0});
export const contract=defineFeatureContract({pluginId:'loops-poc',operations:{
  browse:{kind:'query',description:'Search and browse saved loops in stable pages. view:active includes enabled loops and drafts; runnable includes only authorized published definitions; recoverable includes archived/deleted records and requires author access. Search covers the whole selected view. Follow nextCursor until null; LOOPS_LIBRARY_CHANGED means restart without cursor. Omitting limit returns 50; up to 1000 per page. Existing loops_library/list/deleted array operations remain compatible.',input:Type.Object({view:Type.Optional(Type.Union([Type.Literal('active'),Type.Literal('runnable'),Type.Literal('recoverable')])),search:Type.Optional(Type.String({maxLength:500})),cursor:Type.Optional(Type.String({minLength:1,maxLength:512})),limit:Type.Optional(Type.Integer({minimum:1,maximum:1000}))},object),output:outputs.browse,tool:{name:'loops_browse'}},
  retention:{kind:'action',description:'Preview or apply requested history cleanup for this conversation. Omit applyPlanId to preview; use its planId with the same policy to delete exactly that unchanged candidate set. olderThanDays deletes older terminal runs; keepLatest protects at least that many newest runs. Active, waiting, settling and recovery-parent runs are protected. Loop definitions stay intact. Removed request IDs never execute again. History deletion is permanent; retained transport documents and backups require separate maintenance.',input:Type.Object({policy:RetentionPolicySchema,applyPlanId:Type.Optional(Type.String({pattern:'^[a-f0-9]{64}$'}))},object),output:outputs.retention,tool:{name:'loops_retention'}},
  test:{kind:'action',description:'Execute an unpublished definition with the current caller authority, without changing its draft/publication or activation. Explicit human review nodes still require a real human.',input:Type.Object({definition:toolSchema(DefinitionSchema),input:Type.Record(Type.String(),Type.Unknown()),requestId:Type.Optional(id)},object),output,tool:{name:'loops_test'}},
  retry:{kind:'action',description:'Recover a failed, interrupted or cancelled run with explicit ancestry. checkpoint requires a known committed boundary; retry-node repeats the current node after inspecting possible side effects; restart begins from Input. Wait for cleanup before recovery.',input:Type.Object({runId:id,mode:Type.Union([Type.Literal('checkpoint'),Type.Literal('retry-node'),Type.Literal('restart')]),requestId:Type.Optional(id)},object),output,tool:{name:'loops_retry'}},
  draft:{kind:'action',description:'Save a new draft revision without disabling or changing the published revision. Agents and users have the same control. Publish separately when ready.',input:Type.Object({definition:toolSchema(DefinitionSchema),expectedRevision},object),output:saved,tool:{name:'loops_draft'}},
  versions:{kind:'query',description:'Read immutable revisions of a saved loop, including complete definitions and publication state.',input:Type.Object({id},object),output:outputs.versions,tool:{name:'loops_versions'}},
  publish:{kind:'action',description:'Publish and enable an exact validated revision, preserving the latest draft. Current expectedRevision detects concurrent editing.',input:Type.Object({id,revision,expectedRevision},object),output:outputs.record,tool:{name:'loops_publish'}},
  restore:{kind:'action',description:'Restore an earlier immutable version as a new draft revision. Existing publication and running definitions stay pinned.',input:Type.Object({id,revision,expectedRevision},object),output:saved,tool:{name:'loops_restore'}},
  archive:{kind:'action',description:'Archive or unarchive a loop. Archiving disables new starts and preserves definitions and runs.',input:Type.Object({id,expectedRevision,archived:Type.Boolean()},object),output:outputs.record,tool:{name:'loops_archive'}},
  deleted:{kind:'query',description:'List archived or deleted loops available for recovery.',input:empty,output:outputs.deleted,tool:{name:'loops_deleted'}},
  recover:{kind:'action',description:'Recover a deleted or archived loop as disabled. Publish or enable it separately if requested.',input:Type.Object({id,expectedRevision},object),output:outputs.record,tool:{name:'loops_recover'}},
  output:{kind:'query',description:'Read a full result or node output in Unicode character pages. Follow nextOffset until null; status previews are not the full output.',input:Type.Object({runId:id,nodeId:Type.Optional(id),offset:Type.Optional(Type.Integer({minimum:0})),limit:Type.Optional(Type.Integer({minimum:1,maximum:100000}))},object),output:outputs.output,tool:{name:'loops_output'}},
  history:{kind:'query',description:'Read run history in pages without deleting older runs. Follow nextCursor until null.',input:Type.Object({cursor:Type.Optional(Type.Integer({minimum:0})),limit:Type.Optional(Type.Integer({minimum:1,maximum:1000}))},object),output:outputs.history,tool:{name:'loops_history'}},
  capabilities:{kind:'query',description:'Read effective model and inference parameter capabilities. Advanced fields inherit when omitted; advisory means the runtime may ignore the hint. Unsupported explicit overrides must be reset or require a newer SDK. Zero is an explicit value.',input:Type.Object({model:Type.Optional(Type.String()),agentId:Type.Optional(id)},object),output:outputs.capabilities,tool:{name:'loops_capabilities'}},
  validate:{kind:'query',description:'Validate an editable loop including graph bindings and explicit Advanced overrides without saving or running it.',input:Type.Object({definition:toolSchema(DefinitionSchema)},object),output:outputs.validation,tool:{name:'loops_validate'}},
  list:{kind:'query',description:'List enabled, authorized loops that can run now. For the full library including disabled drafts, use loops_library. Discover a runnable loop here before using loops_run.',input:empty,output:outputs.list,tool:{name:'loops_list'}},
  describe:{kind:'query',description:'Describe an enabled loop, its required inputs, steps and exact revision.',input:Type.Object({slug:id},object),output:outputs.describe,tool:{name:'loops_describe'}},
  run:{kind:'action',description:'Execute a real saved loop. Put named inputs inside input, for example {slug:"summarize-text",input:{text:"Source text"}}. For a single text input, {slug:"summarize-text",text:"Source text"} also works. Omit both for a loop with no inputs. Return the actual result or a pending/failed handle; never simulate. requestId deduplicates retries.',input:Type.Object({slug:id,input:Type.Optional(Type.Record(Type.String(),Type.Unknown())),text:Type.Optional(Type.String()),requestId:Type.Optional(Type.String({minLength:1,maxLength:160}))},object),output,tool:{name:'loops_run'}},
  status:{kind:'query',description:'Inspect the real state and output of a loop run owned by this conversation.',input:runId,output,tool:{name:'loops_status'}},
  resume:{kind:'action',description:'Continue a loop parked at a manual Wait. This never approves a human review.',input:runId,output,tool:{name:'loops_resume'}},
  cancel:{kind:'action',description:'Cancel a loop in this conversation and prevent further node dispatch.',input:runId,output,tool:{name:'loops_cancel'}},
  library:{kind:'query',description:'Read the full saved loop library, including enabled loops and disabled drafts. Returns IDs, slugs, revisions and enablement. Use loops_read for the full editable definition.',input:empty,output:outputs.library,tool:{name:'loops_library'}},
  load:{kind:'query',description:'Read the complete saved loop definition by ID, including all node prompts, edges, layout and current revision, even when disabled. Read before editing or deleting. Runtime grant fields in the result are read-only.',input:Type.Object({id},object),output:outputs.record,tool:{name:'loops_read'}},
  create:{kind:'action',description:'Create a loop when the user requests it. Creates ENABLED by default and grants its declared supported capabilities within host policy; set enabled:false to save a disabled draft instead. Enabling validates the complete graph before saving. Supply a unique slug and editable definition fields; the server assigns identity and revision 1. Read an example with loops_read for a template; omit its id, schemaVersion and revision. Repeat body is Inference then Condition. Use loops_run to actually invoke the saved loop.',input:Type.Object({definition:toolSchema(DefinitionContentSchema),enabled:Type.Optional(Type.Boolean())},object),output:saved,tool:{name:'loops_create'}},
  edit:{kind:'action',description:'Edit a loop when requested. Read first; supply ID, expectedRevision and only changed definition fields. Arrays and objects replace the entire field. Repeat body is Inference then Condition. Preserves enabled/disabled state by default; enabled:true publishes the validated new revision, enabled:false saves a disabled draft. Grants only declared supported capabilities within host policy. Active runs keep their pinned definition. Cannot approve a Human review node.',input:Type.Object({id,expectedRevision:revision,changes:toolSchema(DefinitionPatchSchema),enabled:Type.Optional(Type.Boolean())},object),output:saved,tool:{name:'loops_edit'}},
  delete:{kind:'action',description:'Delete a saved loop only when the user requests deletion. Read it first and supply the current expectedRevision. Refuses loops with active or parked runs; complete or cancel them first. Completed run history is retained. This does not cancel runs or remove other loops.',input:Type.Object({id,expectedRevision:revision},object),output:outputs.deletion,tool:{name:'loops_delete'}},
  save:{kind:'action',description:'Save an editor revision with optimistic concurrency. enabled:true saves and enables atomically; otherwise saves a disabled draft.',input:Type.Object({definition:DefinitionSchema,expectedRevision:Type.Integer({minimum:0}),enabled:Type.Optional(Type.Boolean())},object),output:saved},
  enable:{kind:'action',description:'Enable or disable a saved loop when requested. Read its current ID and revision first. enabled:true validates and grants the loop\'s declared supported capabilities within host policy; no human-only activation step. enabled:false blocks new runs while leaving parked runs controllable. Use loops_run to invoke after enabling. Optional grants is a legacy capability checklist; normally omit it.',input:Type.Object({id,revision,enabled:Type.Boolean(),grants:Type.Optional(Type.Array(Type.Unsafe<Capability>({enum:['llm','model-info']}),{maxItems:2}))},object),output:outputs.record,tool:{name:'loops_enable'}},
  revoke:{kind:'action',description:'Disable a loop and revoke its grants when requested, preventing further host actions in parked runs too. Use loops_enable with enabled:false for ordinary disabling of new runs.',input:Type.Object({id},object),output:outputs.record,tool:{name:'loops_revoke'}},
  runs:{kind:'query',description:'List runs belonging to the selected conversation.',input:empty,output:outputs.runs,tool:{name:'loops_runs'}},
  inspect:{kind:'query',description:'Read complete authorized run evidence, including full outputs, the pinned definition and requested inference settings. Use this when status previews are truncated.',input:runId,output:outputs.completeRun,tool:{name:'loops_inspect'}},
  review:{kind:'action',description:'Record an authenticated human approve/reject decision on the actual stored proposal.',input:Type.Object({runId:id,decision:Type.Union([Type.Literal('approve'),Type.Literal('reject')])},object),output},
},events:{changed:Type.Object({},object)}});
